### ISSUE TITLE
[bjobsusers] Breaks when resolving usernames

### ISSUE THREAD

**Issue by roliveira** [equinor/subscript#505] opened 2022-11-29 12:25 UTC
As it seems `bjobsusers` fails when resolving a few usernames. My usual guess after moving to Norway is that someone with the name containing either Æ, Ø or Å broke the `finger -m username` function call. At times I get the following error:

```python
Traceback (most recent call last):
  File "/prog/res/komodo/2022.10.04-py38-rhel7/root/bin/bjobsusers", line 8, in <module>
    sys.exit(main())
  File "/prog/res/komodo/2022.10.04-py38-rhel7/root/lib/python3.8/site-packages/subscript/bjobsusers/bjobsusers.py", line 169, in main
    show_status("RUN", "Running", umax=args.usercount)
  File "/prog/res/komodo/2022.10.04-py38-rhel7/root/lib/python3.8/site-packages/subscript/bjobsusers/bjobsusers.py", line 142, in show_status
    userinfo(  # lgtm [py/clear-text-logging-sensitive-data]
  File "/prog/res/komodo/2022.10.04-py38-rhel7/root/lib/python3.8/site-packages/subscript/bjobsusers/bjobsusers.py", line 121, in userinfo
    finger_output = finger_function(username)
  File "/prog/res/komodo/2022.10.04-py38-rhel7/root/lib/python3.8/site-packages/subscript/bjobsusers/bjobsusers.py", line 96, in call_finger
    subprocess.check_output(cmd, shell=True, stderr=devnull)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 31: invalid continuation byte
```

**Comment by alifbe** [comment] 2023-04-27 12:57
@roliveira I am having trouble reproducing this issue. I did a couple of testing and it seems to work fine and print users name with the three special Norwegian characters. It might be some other characters.

Can you please record the user short name next time you have this issue again? Perhaps use this command to shorten the list
``bjobs -u all -o "user" | sort | uniq``

**Comment by mferrera** [comment] 2023-08-18 08:28
We've been unable to reproduce this, so closing for now but please reopen if this reoccurs 😄

**Closed by mferrera** 2023-08-18 08:28 UTC
