### ISSUE TITLE
[fmuobs] FutureWarning from dates in Pandas

### ISSUE THREAD

**Issue by berland** [equinor/subscript#479] opened 2022-05-09 13:36 UTC
Running `fmuobs -o yaml ert/test-data/local/snake_oil/observations/observations.txt` yields the warning:

```
/prog/res/komodo/2022.05.00-py38-rhel7/root/lib/python3.8/site-packages/subscript/fmuobs/parsers.py:414: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype={value.dtype})
  return compute_date_from_days(pd.DataFrame(obs_list), starttime)

```

**Comment by mferrera** [comment] 2023-06-22 06:56
Cannot reproduce this and I see https://github.com/equinor/ert/commit/de0fbc21c983d04fc1de0a803f3560ae69f8b882 mitigates it -- @berland do you think this remains an issue, or is it resolved by well formed observation files?

**Comment by berland** [comment] 2023-06-22 07:51
ERT still supports the non-ISO date format, so if a future pandas will fail on such dates, it remains an issue.

**Comment by mferrera** [comment] 2023-09-18 07:17
We can remove the `packaging` dependency (c.f. #598) when fixing up pandas to be 2.0 compliant. It is used here 

https://github.com/equinor/subscript/blob/dae697e92fecf97d4effde7567347575527605d0/src/subscript/ofmvol2csv/ofmvol2csv.py#L268-L276

Should be in the clear now to remove this condition as Komodo is up to pandas 1.5.3 at the time of writing.

**Comment by mferrera** [comment] 2023-09-18 07:19
(I am hijacking this issue to make it a general pandas 2.0 issue 😄)

**Closed** 2023-09-22 05:07 UTC
